{% set version = "4.9.2" %}

package:
  name: easybuild-easyblocks
  version: {{ version }}

source:
  fn: easybuild-easyblocks-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/easybuild-easyblocks/easybuild_easyblocks-{{ version }}.tar.gz
  sha256: 48202a89995a3d0a19228a35e409228bb6aa190ec7d7a7560e449303954953df

build:
  number: 0
  skip: true  # [win or py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - easybuild-framework >=3

test:
  imports:
    - easybuild
    - easybuild.easyblocks
    - easybuild.easyblocks.generic

about:
  home: https://easybuild.io/
  license: GPL-2.0-only
  license_file: LICENSE
  summary: Python modules which implement support for installing particular (groups of) software packages with EasyBuild.

extra:
  recipe-maintainers:
    - jerowe
    - boegel
