{% set version = "4.4.1" %}

package:
  name: easybuild-easyblocks
  version: {{ version }}

source:
  fn: easybuild-easyblocks-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/easybuild-easyblocks/easybuild-easyblocks-{{ version }}.tar.gz
  sha256: de5a203a60ee14ea1c2e56ed34f21fc0f94670214e9f8818a24ebf9d78ba656e

build:
  number: 0
  skip: true  # [win or py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - easybuild-framework >=3

test:
  imports:
    - easybuild
    - easybuild.easyblocks
    - easybuild.easyblocks.generic

about:
  home: http://hpcugent.github.com/easybuild
  license: GPLv2
  license_file: LICENSE
  summary: Python modules which implement support for installing particular (groups of) software packages with EasyBuild.
  license_family: GPL2

extra:
  recipe-maintainers:
    - jerowe
    - boegel
