{% set version = "3.8.0" %}

package:
  name: easybuild-easyblocks
  version: {{ version }}

source:
  fn: easybuild-easyblocks-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/easybuild-easyblocks/easybuild-easyblocks-{{ version }}.tar.gz
  sha256: aa9800f2eabb60683ad2ac76b789385b5a28516fbdfc8da87d8e98ae0e16cb57

build:
  number: 1000
  skip: True  # [win or py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - easybuild-framework >=3

test:
  imports:
    - easybuild
    - easybuild.easyblocks
    - easybuild.easyblocks.generic

about:
  home: http://hpcugent.github.com/easybuild
  license: GPLv2
  license_file: LICENSE
  summary: 'Python modules which implement support for installing particular (groups of) software packages with EasyBuild.'
  license_family: GPL2

extra:
  recipe-maintainers:
    - jerowe
    - boegel
