appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: oCwh/98FZRMNqlIjYof3qd/HM4p7OrCbgP9cMmPxAJjiKcOJPvQiK8iQGRySkWfO5uGVrhzylCfLu4qD62/hoQ43u6BEFUnJ0ChuaKWNXajp8PKW07nC1UQ3IU1+ZSyV19rK6fqu7URJqoSia/SyH5TqbHvDQRLUiQOOv9U5ATWCXWmLX4vR5G0Qwcr4igGrKDMCS63YJ4TpOourE8l6qOHrfuGoQRtT/8HK8MZc++8w8Op9LxXNlJkvf3BWw4GSCrpYvOb59RlMuumk3w4vuCcK62ezFGogH6le50FFtGf0UiELvWdMZW3xTcCNHZIImoBfVATZcK2Y0cRl/c5M9NqXqVgeSCeyWUyp9I1v30EDgKVwyIX/Eq615+rQ0H9fzcV0IkoVInhumAJ0iKQptP7h6OdmBvAvit+GtY1Umrjl9poOwORJ+YFjPTyAmIr6Md33Bui88TeayDR7xOo1MpNuVsz6beEAVeVjgEF5Erfo750YjS6u8CpACsmvseI9C/XFjkNukhH3t15+7YwpjBPC9rx46t8SN3So8BE2Uj6Ish17WSxPiq9t9qxPno6cEvYkmgVJ3aUCJQTZYRFgSrtwyqyW0AzDRpwJZEwnwI+1W29z6JW4uLJILt7mGrCLYh8KadncHoYul1gaM5874Qdn21sQdFAIkoXDKKH3jAg=}
conda_forge_output_validation: true
