travis:
  secure:
    BINSTAR_TOKEN: CEobhGMXlx1Ed4PwtuPVuu3nFtj/DXkwq9aYvbUFyRvTA+b5IZ5DrP3eUdCoNavmWSIxxMvsQ1+ilKxiQwM81T8fxR1pIJYoAuQPpUq/l1SR3JCYzFYH4pBJJT3pKVpZyRgNiOYyRKFmarczEpEOILe3X7Y5YT4P3bDVnG6cH8s6Xq3qYqYxxB/vE+fnH0QSMfxtCBF10JdEjmOKNB7QSNEuLKnHKQLHcXZ0eSpSC534OpdpU2XVSyWrgA6UQIrDyb7OiDKN+jlwfh3BZnU8zB1+Yg/KkAp0cJ1KwLY9DVf9qbhseqKi6hj59QzlR0qfyhmCknEuJrEEgUdoygbrlebDo74Spjrsm2JrDiUXKVPEuWpjlMUGFt5rDUJriVslDIG0Qc8B/+yr9fzdQ7pdQUPj88KBE2Dq8A4SYjQdFdz/zdWGGQ8i2JW3lOqL3thvu2VFysLzCWM4y2+GZSwZftzveOoYPthuzQre/t99ccy21hHQLK4/98UU+lgE/tkD2eLikg5gsWm+njoz2Dsy5AOCw4lHGkljX+4pchFRuPFH2/K7qN76SMd1JcYt7zuxCF+BkLStkVE8zCWKt2gCISsMrVtHMoSpg3K3mg7bUcTY5lOt1FjrvZbst+VHj4OtPW65HD44uXiKdZNIQjUNb/aYN9uZVTHvEYT0y/cwZu4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
